class EnemyInterface:
    IMAGE_PATH_WALK = ...
    SPEED = ...
    TIMER_WALK_ANIM = ...

    def death(self):
        ...

    def attack(self):
        ...

    def chase_player(self):
        ...
